site_name: Ívna Projetos
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: default
    primary: red
    accent: cyan
  font:
    text: Outfit
    code: Outfit Mono

plugins:
  - blog