site_name: Projetos
site_url: https://ivnamabreu.github.io/ivna-projetos/
theme:
  name: material
  palette:
    scheme: default
    primary: red
    accent: cyan
  font:
    text: Outfit
    code: Outfit Mono

plugins:
  - blog